packages:
  - '.'

engineStrict: true
resolutionMode: highest
minimumReleaseAge: 0
nodeLinker: hoisted
overrides:
  '@esbuild-kit/core-utils>esbuild': 0.25.12
  cookie: 0.7.2
allowBuilds:
  esbuild: true
  svelte-preprocess: true
